"use strict";

/*
* File is used to store Bridge Server API
* URL of Bridge Server
* Service provided by Bridge Server
*/

module.exports = {

  "assetsCode": "USD",
  "memo_type": "text",
  "assetIssuer": "GAPXSAEHK7GCW7WPMJE5QTCTDAGEFIQO2K3JPXAFADPYGG352GBYENDV",
  "receiver": "GDUN2CT6F75OD4AACSJTDRHWQLWBOEYUCS2XPKKFBHJQDDD7TGHWGC3N",
  "destination": "GDUN2CT6F75OD4AACSJTDRHWQLWBOEYUCS2XPKKFBHJQDDD7TGHWGC3N",
  "source": "SDCWMDQNM2ZOPB4YHQOQLR7LI3UEC36AJ3GGYKGNJNGKTZPFUZZODGO7",
  "sourceKeys": "SDCWMDQNM2ZOPB4YHQOQLR7LI3UEC36AJ3GGYKGNJNGKTZPFUZZODGO7",
  "destinationId": "GDUN2CT6F75OD4AACSJTDRHWQLWBOEYUCS2XPKKFBHJQDDD7TGHWGC3N"

};